package fr.insee.rmes.persistance.service.sesame.operations.series;

import java.util.List;

import fr.insee.rmes.config.swagger.model.IdLabelTwoLangs;
import fr.insee.rmes.exceptions.RmesException;
import fr.insee.rmes.persistance.service.sesame.links.OperationsLink;
import fr.insee.rmes.persistance.service.sesame.operations.famOpeSerUtils.famOpeSerUtils;
import io.swagger.v3.oas.annotations.media.Schema;

public class Series {

	@Schema(description = "Id", required = true)
	public String id;

	@Schema(description = "Label lg1", required = true)
	public String prefLabelLg1;

	@Schema(description = "Label lg2")
	public String prefLabelLg2;

	@Schema(description = "Alternative label Lg1")
	public String altLabelLg1;

	@Schema(description = "Alternative label Lg2")
	public String altLabelLg2;

	@Schema(description = "Abstract Lg1")
	public String abstractLg1;


	@Schema(description = "Abstract lg2")
	public String abstractLg2;
	
	@Schema(description = "History note Lg1")
	public String historyNoteLg1;


	@Schema(description = "History note lg2")
	public String historyNoteLg2;

	@Schema(description = "Family")
	public IdLabelTwoLangs family;

	@Schema(description = "Operations")
	public List<IdLabelTwoLangs> operations;

	@Schema(description = "Type's notation")
	public String typeCode;

	@Schema(description = "Type list's notation")
	public String typeList;

	@Schema(description = "Frequency's notation")
	public String accrualPeriodicityCode;

	@Schema(description = "Frequencies list's notation")
	public String accrualPeriodicityList;

	@Schema(description = "Identifier of creator")
	public String creator;

	@Schema(description = "Identifiers of contributors")
	public List<OperationsLink> contributor;

	@Schema(description = "Identifiers of data collector")
	public List<OperationsLink> dataCollector;

	@Schema(description = "Identifier of gestionnaire")
	public String gestionnaire;
	
	@Schema(description = "List of resources to see also")
	public List<OperationsLink> seeAlso;

	@Schema(description = "List of resources that replaces the series")
	public List<OperationsLink> replaces;
		
	@Schema(description = "List of resources generated by the series")
	public List<OperationsLink> generates;
		
	@Schema(description = "List of resources replaced by the series")
	public List<OperationsLink> isReplacedBy;
	
	
	/*
	 * Constructors
	 */
	
	public Series() throws RmesException {
		this.id=  famOpeSerUtils.createId();
}	
	
	public Series(String id) {
		this.id=id;
	}

	/*
	 * Getters
	 */
	
	public String getId() {
		return id;
	}

	public String getPrefLabelLg1() {
		return prefLabelLg1;
	}

	public String getPrefLabelLg2() {
		return prefLabelLg2;
	}

	public String getAltLabelLg1() {
		return altLabelLg1;
	}

	public String getAltLabelLg2() {
		return altLabelLg2;
	}

	public String getAbstractLg1() {
		return abstractLg1;
	}

	public String getAbstractLg2() {
		return abstractLg2;
	}

	

	public String getHistoryNoteLg1() {
		return historyNoteLg1;
	}

	public String getHistoryNoteLg2() {
		return historyNoteLg2;
	}
	public IdLabelTwoLangs getFamily() {
		return family;
	}

	public List<IdLabelTwoLangs> getOperations() {
		return operations;
	}

	public String getTypeCode() {
		return typeCode;
	}

	public String getTypeList() {
		return typeList;
	}

	public String getAccrualPeriodicityCode() {
		return accrualPeriodicityCode;
	}

	public String getAccrualPeriodicityList() {
		return accrualPeriodicityList;
	}

	public String getCreator() {
		return creator;
	}

	public List<OperationsLink> getContributor() {
		return contributor;
	}

	public List<OperationsLink> getDataCollector() {
		return dataCollector;
	}

	public String getGestionnaire() {
		return gestionnaire;
	}

	public List<OperationsLink> getSeeAlso() {
		return seeAlso;
	}

	public List<OperationsLink> getReplaces() {
		return replaces;
	}

	public List<OperationsLink> getIsReplacedBy() {
		return isReplacedBy;
	}



}
