name: bauhaus
services:
  bauhaus-back:
    build: .
    ports:
      - "8080:8080"
    links:
      - graphdb:localhost
  graphdb:
    image: ontotext/graphdb:10.6.4
    restart: always
    ports:
      - "7200:7200"
    environment:
      GDB_JAVA_OPTS: "-Xmx1g -Xms512M"
