apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bauhaus-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - bauhaus-api.toto.fr
  rules:
    - host: bauhaus-api.toto.fr
      http:
        paths:
          - path: /
            backend:
              serviceName: bauhaus-api
              servicePort: http
