package fr.insee.rmes.exceptions.errors;

public class IndicatorErrorCode {

    private IndicatorErrorCode() {
    }

    public static final String EMPTY_WAS_GENERATED_BY = "406_OPERATION_INDICATOR_OPERATION_INDICATOR_EMPTY_WAS_GENERATED_BY";
    public static final String VALIDATION_UNVALIDATED_SERIES = "OPERATION_INDICATOR_VALIDATION_UNVALIDATED_SERIES";
    public static final String EXISTING_PREF_LABEL_LG1 = "406_OPERATION_INDICATOR_OPERATION_INDICATOR_EXISTING_PREF_LABEL_LG1";
    public static final String EXISTING_PREF_LABEL_LG2 = "406_OPERATION_INDICATOR_OPERATION_INDICATOR_EXISTING_PREF_LABEL_LG2";

}
