name: Quality
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test-build:
    name: Test & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Branches
        uses: actions/github-script@v6
        with:
          script: context.payload.pull_request.base.ref === 'main' && context.payload.pull_request.head.ref !== 'acceptance' && core.setFailed("A PR to the main branch must come from the acceptance branch, but comes from " + context.payload.pull_request.head.ref);  
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
        - name: Build with Maven
          run: mvn test