name: Build Beta

on:
  release:
    types: [prereleased]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./Dockerfile.bauhaus
          tags: ghcr.io/inseefr/bauhaus-back-office:${{ github.event.release.tag_name }}
